field: f9662815-850c-43a1-8dbc-a0049bab76f8
fieldLayouts:
  763af57a-1b8b-44b3-a6c0-466d46d9266b:
    tabs:
      -
        elements:
          -
            fieldUid: e253aa26-3e38-462b-8c01-9b6fcf163df7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6eb08eae-6f58-4839-a6ec-4b96a1c6ac42
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6eb08eae-6f58-4839-a6ec-4b96a1c6ac42:
    contentColumnType: text
    fieldGroup: null
    handle: contactInput
    instructions: ''
    name: 'Contact input'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e253aa26-3e38-462b-8c01-9b6fcf163df7:
    contentColumnType: string
    fieldGroup: null
    handle: contactIcon
    instructions: ''
    name: 'Contact icon'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Adress
            -
              - value
              - 'fas fa-home mr-3'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - E-mail
            -
              - value
              - 'fas fa-envelope mr-3'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Phone
            -
              - value
              - 'fas fa-phone mr-3'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Fax
            -
              - value
              - 'fas fa-print mr-3'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: contactInfo
name: 'Contact info'
sortOrder: 1
