fieldLayouts:
  25b3d0a8-7c85-4879-9246-4b629b3cdc91:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: __blank__
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: e4cdfe89-3938-4f38-a5a6-06b9b2c3c7ef
            instructions: ''
            label: Name
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5d8b7b7a-2de9-4075-a860-7f4b8b328d85
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c9505970-5427-4d98-920a-eace1edd99de
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cc8f74bc-5010-4b72-8473-e5a1b33a207e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 42d05a74-4bf8-4dd1-9315-d4e160911371
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: comments
hasTitleField: false
name: Comments
section: d20cdcac-ad5b-476f-873a-d5dce6699c1c
sortOrder: 1
titleFormat: comments
titleTranslationKeyFormat: null
titleTranslationMethod: site
