fieldLayouts:
  8cc3e150-7eda-4df7-8c8b-a888b59a70dc:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 2355d39d-47da-4e82-b50a-e099208d5eee
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c3912c0d-5273-4027-8ea7-74c0ca7ec838
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6df19862-1703-4ac0-885f-3243d0e836ba
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5f1aae22-caf5-4f32-9f29-2d98911d9794
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: featuredPosts
hasTitleField: false
name: featured_posts
section: 781e79e2-1775-447f-ba58-7f23eb2b6cd7
sortOrder: 1
titleFormat: 'featured posts'
titleTranslationKeyFormat: null
titleTranslationMethod: site
