fieldLayouts:
  d7f85aee-96f0-4f55-a7d6-86a437ba7bec:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 2355d39d-47da-4e82-b50a-e099208d5eee
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: instagram
hasTitleField: false
name: instagram
section: 00b50a20-0dac-49c3-9360-cb30ccf1eb07
sortOrder: 1
titleFormat: 'follow me'
titleTranslationKeyFormat: null
titleTranslationMethod: site
