fieldLayouts:
  f6d55880-ad0a-4dfd-8a02-2bfa54229197:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: newsletter
hasTitleField: false
name: Newsletter
section: d2d73eda-3c35-430a-ad72-a7a9f3aa80b9
sortOrder: 2
titleFormat: email
titleTranslationKeyFormat: null
titleTranslationMethod: site
