fieldLayouts:
  7c861024-12f5-4e0b-a304-c5accfd9a878:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: d3ce8025-e5af-4ccf-b4e6-ca2068752f3e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: page
hasTitleField: true
name: Page
section: e28b7518-65aa-4895-a1ad-22d4bfdd8236
sortOrder: 1
titleFormat: page
titleTranslationKeyFormat: null
titleTranslationMethod: site
