fieldLayouts:
  cd077675-5f1f-4ae3-a3c8-3b5507286a5a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: articlesCategory
name: 'Articles category'
siteSettings:
  0c2d02e9-1d1e-4615-a309-ed793efd7840:
    hasUrls: true
    template: null
    uriFormat: 'articlescat/{slug}'
structure:
  maxLevels: null
  uid: 50a1504f-f889-4c80-b088-35f7a40fd182
