contentColumnType: string
fieldGroup: 02935152-90f1-4de0-b483-3eebcce502e7
handle: category
instructions: ''
name: Category
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Lifestyle
        -
          - value
          - lifestyle
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Travel
        -
          - value
          - travel
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Work
        -
          - value
          - work
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Fashion
        -
          - value
          - fashion
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
