contentColumnType: string
fieldGroup: 02935152-90f1-4de0-b483-3eebcce502e7
handle: contact
instructions: ''
name: Contact
searchable: false
settings:
  contentTable: '{{%matrixcontent_contact}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
