contentColumnType: string
fieldGroup: 02935152-90f1-4de0-b483-3eebcce502e7
handle: socialLinks
instructions: ''
name: social_links
searchable: false
settings:
  contentTable: '{{%matrixcontent_sociallinks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
