contentColumnType: string
fieldGroup: 02935152-90f1-4de0-b483-3eebcce502e7
handle: subscriber
instructions: ''
name: Subscriber
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
