fieldLayouts:
  2a0c2345-1c12-43f2-87cd-c2dff184cd97:
    tabs:
      -
        elements:
          -
            fieldUid: d2e8d0f8-0d6e-4505-81e3-9df640eeb6e3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 13214b9a-f74a-49ae-a3d3-8897e1567701
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 022ce921-a33d-4abb-a440-d513d82cb32e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 76a9fb08-491e-4b63-8a21-e60dc2605e25
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: layout
name: layout
