fieldLayouts:
  008be8e1-43e3-4880-a685-80eb5516c673:
    tabs:
      -
        elements:
          -
            fieldUid: 7e0cbfd5-23cc-42e0-9ae9-338c7c7d3298
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: socialNetworks
name: social_networks
