enableVersioning: true
handle: navbar
name: Navbar
propagationMethod: all
siteSettings:
  0c2d02e9-1d1e-4615-a309-ed793efd7840:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
