enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - 'homepage/{slug}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0c2d02e9-1d1e-4615-a309-ed793efd7840:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'pages/{slug}'
type: channel
